<?php if (!defined('BASEPATH')) exit('No direct script access allowed');



/* Mst_tahanan.php */
/* HARVIACODE CRUD GENERATOR MVC/HMVC AJAX CRUD */
/* PENGEMBANG : MPAMPAM */
/* EMAIL : MPAMPAM5@GMAIL.COM */
/* FACEBOOK : https://www.facebook.com/mpampam */
/* Location: ./application/controllers/Mst_tahanan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-07-01 18:15:21 */
/* http://harviacode.com */

 class Mst_tahanan extends MY_Controller{
  function __construct(){
      parent::__construct();
      $this->load->model('Mst_tahanan_model','model');
      $this->load->library("Cl");
      if ($this->cl->acl(config_item("cpanel")."mst_tahanan")==false) {
        redirect("errors/er403");
      }
  }

 function _rules(){
		$this->form_validation->set_rules('id_tahanan', 'id_tahanan', 'trim');
		$this->form_validation->set_rules('nama', 'nama', 'trim|xss_clean|required');
		$this->form_validation->set_rules('tempat_lahir', 'tempat lahir', 'trim|xss_clean|required');
		$this->form_validation->set_rules('tgl_lahir', 'tgl lahir', 'trim|xss_clean|required');
		$this->form_validation->set_rules('jenis_kelamin', 'jenis kelamin', 'trim|xss_clean|required');
		$this->form_validation->set_rules('kebangsaan', 'kebangsaan', 'trim|xss_clean|required');
		$this->form_validation->set_rules('id_agama', 'agama', 'trim|xss_clean|required');
		$this->form_validation->set_rules('pekerjaan', 'pekerjaan', 'trim|xss_clean|required');
		$this->form_validation->set_rules('alamat', 'alamat', 'trim|xss_clean|required');
		$this->form_validation->set_rules('foto', 'foto', 'trim|xss_clean');
		$this->form_validation->set_error_delimiters('<span class="text-danger"><label class="label label-danger">', '</label></span>');
  }

 function index(){
    $this->layouts->set_title('Tahanan');
    $this->layouts->view(config_item("cpanel").'content/mst_tahanan/index');
  }

function json() {
    header('Content-Type: application/json');
    echo $this->model->json();
}


 function detail($id){
    if($row=$this->model->get_where($id)){
      $this->layouts->set_title('Tahanan');
        $data=array('layout_title' => 'Tahanan',
										'id_tahanan' => $row->id_tahanan,
										'nik' => $row->nik,
										'nama' => $row->nama,
										'tempat_lahir' => $row->tempat_lahir,
										'tgl_lahir' => $row->tgl_lahir,
										'jenis_kelamin' => $row->jenis_kelamin,
										'kebangsaan' => $row->kebangsaan,
										'id_agama' => $row->id_agama,
										'pekerjaan' => $row->pekerjaan,
										'alamat' => $row->alamat,
										'foto' => $row->foto,
										'created_at' => $row->created_at,
										'update_at' => $row->update_at,
										'created_by' => $row->created_by,
										'update_by' => $row->update_by,
									);
				 $this->layouts->view(config_item("cpanel").'content/mst_tahanan/detail',array(),$data);
//MODAL DETAIL
//$this->layouts->view(config_item("cpanel").'content/mst_tahanan/detail',array(),$data,false);
    }else {
        $this->error_404();
    }
  }

 function tambah($status=''){
    if ($status=='aksi') {
        $json = array('success'=>false ,'alert'=>array());
        if ($this->input->is_ajax_request()) {
            $this->form_validation->set_rules('nik', 'nik', 'trim|xss_clean|required|numeric|callback_nik_insert');
            $this->_rules();
            if ($this->form_validation->run()) {
                $insert = array(
																'nik' => $this->input->post('nik',TRUE),
																'nama' => $this->input->post('nama',TRUE),
																'tempat_lahir' => $this->input->post('tempat_lahir',TRUE),
																'tgl_lahir' => $this->input->post('tgl_lahir',TRUE),
																'jenis_kelamin' => $this->input->post('jenis_kelamin',TRUE),
																'kebangsaan' => $this->input->post('kebangsaan',TRUE),
																'id_agama' => $this->input->post('id_agama',TRUE),
																'pekerjaan' => $this->input->post('pekerjaan',TRUE),
																'alamat' => $this->input->post('alamat',TRUE),
																'foto' => $this->input->post('foto',TRUE),
                                'created_at' => date('Y-m-d h:i:s'),
																'created_by' => sess('id_auth')
															);
                $this->model->get_insert($insert);
                $json['alert']   = 'Berhasil Menyimpan!';
                $json['success'] = true;
            }else{
                foreach ($_POST as $key => $value) {
                  $json['alert'][$key] = form_error($key);
                }
            }
            echo json_encode($json);
        }
    }else{
      $this->layouts->set_title('Tahanan');
      $data = array('layout_title' => 'Tahanan',
                      'button'=>'tambah',
                      'aksi' =>site_url(config_item("cpanel").'mst_tahanan/tambah/aksi'),
											'id_tahanan' => set_value('id_tahanan'),
											'nik' => set_value('nik'),
											'nama' => set_value('nama'),
											'tempat_lahir' => set_value('tempat_lahir'),
											'tgl_lahir' => set_value('tgl_lahir'),
											'jenis_kelamin' => set_value('jenis_kelamin'),
											'kebangsaan' => set_value('kebangsaan'),
											'id_agama' => set_value('id_agama'),
											'pekerjaan' => set_value('pekerjaan'),
											'alamat' => set_value('alamat'),
											'foto' => set_value('foto')
											);
			 $this->layouts->view(config_item("cpanel").'content/mst_tahanan/form',array(),$data);
  //MODAL TAMBAH
  //$this->layouts->view(config_item("cpanel").'content/mst_tahanan/form',array(),$data,false);
     }
  }

 function edit($id,$status=''){
      if ($status=='aksi') {
          $json = array('success'=>false ,'alert'=>array());
          if ($this->input->is_ajax_request()) {
              $nik_hide = $this->input->post('nik_hidden');
              $this->form_validation->set_rules('nik', 'nik', 'trim|xss_clean|required|numeric|callback_nik_update['.$nik_hide.']');
              $this->_rules();
              if ($this->form_validation->run()) {
                  $update = array(
																'nik' => $this->input->post('nik',TRUE),
																'nama' => $this->input->post('nama',TRUE),
																'tempat_lahir' => $this->input->post('tempat_lahir',TRUE),
																'tgl_lahir' => $this->input->post('tgl_lahir',TRUE),
																'jenis_kelamin' => $this->input->post('jenis_kelamin',TRUE),
																'kebangsaan' => $this->input->post('kebangsaan',TRUE),
																'id_agama' => $this->input->post('id_agama',TRUE),
																'pekerjaan' => $this->input->post('pekerjaan',TRUE),
																'alamat' => $this->input->post('alamat',TRUE),
																'foto' => $this->input->post('foto',TRUE),
                                'update_at' => date('Y-m-d h:i:s'),
																'update_by' => sess('id_auth')
															);
                $this->model->get_update($id,$update);
                $json['alert']   = 'Berhasil Mengedit!';
                $json['success'] = true;
            }else{
                foreach ($_POST as $key => $value) {
                  $json['alert'][$key] = form_error($key);
                }
            }
            echo json_encode($json);
        }
    }else{
      if($row=$this->model->get_where($id)){
        $this->layouts->set_title('Tahanan');
        $data = array('layout_title' => 'Tahanan',
                      'button'=>'edit',
                      'aksi' =>site_url(config_item("cpanel").'mst_tahanan/edit/'.$id.'/aksi'),
											'id_tahanan' => set_value('id_tahanan', $row->id_tahanan),
											'nik' => set_value('nik', $row->nik),
											'nama' => set_value('nama', $row->nama),
											'tempat_lahir' => set_value('tempat_lahir', $row->tempat_lahir),
											'tgl_lahir' => set_value('tgl_lahir', $row->tgl_lahir),
											'jenis_kelamin' => set_value('jenis_kelamin', $row->jenis_kelamin),
											'kebangsaan' => set_value('kebangsaan', $row->kebangsaan),
											'id_agama' => set_value('id_agama', $row->id_agama),
											'pekerjaan' => set_value('pekerjaan', $row->pekerjaan),
											'alamat' => set_value('alamat', $row->alamat),
											'foto' => set_value('foto', $row->foto),
											);
			 $this->layouts->view(config_item("cpanel").'content/mst_tahanan/form',array(),$data);
  //MODAL EDIT
  //$this->layouts->view(config_item("cpanel").'content/mst_tahanan/form',array(),$data,false);
			}else{
      $this->error_404();
    }
  }
}

 function hapus($id){
  if ($this->input->is_ajax_request()) {
    if ($this->model->get_delete($id)==false) {
      $data['alert'] = 'Gagal menghapus, data ini terpakai di table lain!';
    }else {
      $data['alert'] = 'Berhasil menghapus!';
    }
      echo json_encode($data);
    }
}



function nik_insert($str)
{
  $query = $this->db->get_where("mst_tahanan",array("nik"=>$str));
  if ($query->num_rows()>0) {
    $this->form_validation->set_message('nik_insert', '{field} &nbsp;<a target="_blank" href="detail/'.$query->row()->id_tahanan.'"><i>'.$str.'</i></a>&nbsp; sudah ada!');
    return FALSE;
  }else {
    return TRUE;
  }
}

function nik_update($str, $nik_hidden)
{
  if ($str==$nik_hidden) {
    return TRUE;
  }else {
    $query = $this->db->get_where("mst_tahanan",array("nik"=>$str));
    if ($query->num_rows()>0) {
      $this->form_validation->set_message('nik_update', '{field} &nbsp;<a target="_blank" href="../detail/'.$query->row()->id_tahanan.'"><i>'.$str.'</i></a>&nbsp; sudah ada!');
      return FALSE;
    }else {
      return TRUE;
    }
  }

}

}
/* End Controller */
