<?php if (!defined('BASEPATH')) exit('No direct script access allowed');



/* Mst_dokter.php */
/* HARVIACODE CRUD GENERATOR MVC/HMVC AJAX CRUD */
/* PENGEMBANG : MPAMPAM */
/* EMAIL : MPAMPAM5@GMAIL.COM */
/* FACEBOOK : https://www.facebook.com/mpampam */
/* Location: ./application/controllers/Mst_dokter.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-09-18 18:41:17 */
/* http://harviacode.com */

 class Mst_dokter extends MY_Controller{
  function __construct(){
      parent::__construct();
      $this->load->model('Mst_dokter_model','model');
      $this->load->library("Cl");
      if ($this->cl->acl(config_item("cpanel")."mst_dokter")==false) {
        redirect("errors/er403");
      }
  }

 function _rules(){
		$this->form_validation->set_rules('nama', 'nama', 'trim|xss_clean|required');
		$this->form_validation->set_rules('tempat_lhr', 'tempat lhr', 'trim|xss_clean');
		$this->form_validation->set_rules('tgl_lhr', 'tgl lhr', 'trim|xss_clean');
		$this->form_validation->set_rules('telepon', 'telepon', 'trim|xss_clean|numeric');
		$this->form_validation->set_rules('alamat', 'alamat', 'trim|xss_clean');
		$this->form_validation->set_rules('alumni', 'alumni', 'trim|xss_clean');

		$this->form_validation->set_error_delimiters('<span class="text-danger"><label class="label label-danger">', '</label></span>');
  }

 function index(){
    $this->layouts->set_title('Pemeriksa');
    $this->layouts->view(config_item("cpanel").'content/mst_dokter/index');
  }

function json() {
    header('Content-Type: application/json');
    echo $this->model->json();
}


 function detail($id){
    if($row=$this->model->get_where($id)){
      $this->layouts->set_title('Pemeriksa');
        $data=array('layout_title' => 'Pemeriksa',
										'id_pemeriksa' => $row->id_pemeriksa,
										'nik' => $row->nik,
										'nama' => $row->nama,
										'tempat_lhr' => $row->tempat_lhr,
										'tgl_lhr' => $row->tgl_lhr,
										'telepon' => $row->telepon,
										'alamat' => $row->alamat,
										'alumni' => $row->alumni,
										'created_at' => $row->created_at,
										'update_at' => $row->update_at,
										'created_by' => $row->created_by,
									);
				// $this->layouts->view(config_item("cpanel").'content/mst_dokter/detail',array(),$data);
//MODAL DETAIL
$this->layouts->view(config_item("cpanel").'content/mst_dokter/detail',array(),$data,false);
    }else {
        $this->error_404();
    }
  }

 function tambah($status=''){
    if ($status=='aksi') {
        $json = array('success'=>false ,'alert'=>array());
        if ($this->input->is_ajax_request()) {
            $this->form_validation->set_rules('nik', 'nik', 'trim|xss_clean|required|numeric|callback_nik_insert');
            $this->_rules();
            if ($this->form_validation->run()) {
                $insert = array(
																'nik' => $this->input->post('nik',TRUE),
																'nama' => $this->input->post('nama',TRUE),
																'tempat_lhr' => $this->input->post('tempat_lhr',TRUE),
																'tgl_lhr' => $this->input->post('tgl_lhr',TRUE),
																'telepon' => $this->input->post('telepon',TRUE),
																'alamat' => $this->input->post('alamat',TRUE),
																'alumni' => $this->input->post('alumni',TRUE),
                                'created_at' => date('Y-m-d h:i:s'),
																'created_by' => sess('id_auth')
															);
                $this->model->get_insert($insert);
                $json['alert']   = 'Berhasil Menyimpan!';
                $json['success'] = true;
            }else{
                foreach ($_POST as $key => $value) {
                  $json['alert'][$key] = form_error($key);
                }
            }
            echo json_encode($json);
        }
    }else{
      $this->layouts->set_title('Pemeriksa');
      $data = array('layout_title' => 'Pemeriksa',
                      'button'=>'tambah',
                      'aksi' =>site_url(config_item("cpanel").'mst_dokter/tambah/aksi'),
											'id_pemeriksa' => set_value('id_pemeriksa'),
											'nik' => set_value('nik'),
											'nama' => set_value('nama'),
											'tempat_lhr' => set_value('tempat_lhr'),
											'tgl_lhr' => set_value('tgl_lhr'),
											'telepon' => set_value('telepon'),
											'alamat' => set_value('alamat'),
											'alumni' => set_value('alumni'),
											'created_at' => set_value('created_at'),
											'update_at' => set_value('update_at'),
											'created_by' => set_value('created_by'),
											);
			 $this->layouts->view(config_item("cpanel").'content/mst_dokter/form',array(),$data);
  //MODAL TAMBAH
  //$this->layouts->view(config_item("cpanel").'content/mst_dokter/form',array(),$data,false);
     }
  }

 function edit($id,$status=''){
      if ($status=='aksi') {
          $json = array('success'=>false ,'alert'=>array());
          if ($this->input->is_ajax_request()) {
            $nik_hide = $this->input->post('nik_hidden');
            $this->form_validation->set_rules('nik', 'nik', 'trim|xss_clean|required|numeric|callback_nik_update['.$nik_hide.']');
              $this->_rules();
              if ($this->form_validation->run()) {
                  $update = array(
																'nik' => $this->input->post('nik',TRUE),
																'nama' => $this->input->post('nama',TRUE),
																'tempat_lhr' => $this->input->post('tempat_lhr',TRUE),
																'tgl_lhr' => $this->input->post('tgl_lhr',TRUE),
																'telepon' => $this->input->post('telepon',TRUE),
																'alamat' => $this->input->post('alamat',TRUE),
																'alumni' => $this->input->post('alumni',TRUE),
                                'update_at' => date('Y-m-d h:i:s')
															);
                $this->model->get_update($id,$update);
                $json['alert']   = 'Berhasil Mengedit!';
                $json['success'] = true;
            }else{
                foreach ($_POST as $key => $value) {
                  $json['alert'][$key] = form_error($key);
                }
            }
            echo json_encode($json);
        }
    }else{
      if($row=$this->model->get_where($id)){
        $this->layouts->set_title('Pemeriksa');
        $data = array('layout_title' => 'Pemeriksa',
                      'button'=>'edit',
                      'aksi' =>site_url(config_item("cpanel").'mst_dokter/edit/'.$id.'/aksi'),
											'id_pemeriksa' => set_value('id_pemeriksa', $row->id_pemeriksa),
											'nik' => set_value('nik', $row->nik),
											'nama' => set_value('nama', $row->nama),
											'tempat_lhr' => set_value('tempat_lhr', $row->tempat_lhr),
											'tgl_lhr' => set_value('tgl_lhr', $row->tgl_lhr),
											'telepon' => set_value('telepon', $row->telepon),
											'alamat' => set_value('alamat', $row->alamat),
											'alumni' => set_value('alumni', $row->alumni),
											);
			 $this->layouts->view(config_item("cpanel").'content/mst_dokter/form',array(),$data);
  //MODAL EDIT
  //$this->layouts->view(config_item("cpanel").'content/mst_dokter/form',array(),$data,false);
			}else{
      $this->error_404();
    }
  }
}

 function hapus($id){
  if ($this->input->is_ajax_request()) {
        if ($this->model->get_delete($id)==false) {
          $data['alert'] = 'Gagal Menghapus, data ini terpakai di table lain!';
        }else {
          $data['alert'] = 'Berhasil Menghapus!';
        }
      echo json_encode($data);
    }
}

function nik_insert($str)
{
  $query = $this->db->get_where("mst_dokter",array("nik"=>$str));
  if ($query->num_rows()>0) {
    $this->form_validation->set_message('nik_insert', 'Nik/Nrp &nbsp;<a target="_blank" href="detail/'.$query->row()->id_pemeriksa.'"><i>'.$str.'</i></a>&nbsp; sudah ada!');
    return FALSE;
  }else {
    return TRUE;
  }
}

function nik_update($str, $nik_hidden)
{
  if ($str==$nik_hidden) {
    return TRUE;
  }else {
    $query = $this->db->get_where("mst_dokter",array("nik"=>$str));
    if ($query->num_rows()>0) {
      $this->form_validation->set_message('nik_update', 'Nik/Nrp &nbsp;<a target="_blank" href="../detail/'.$query->row()->id_pemeriksa.'"><i>'.$str.'</i></a>&nbsp; sudah ada!');
      return FALSE;
    }else {
      return TRUE;
    }
  }

}




}
/* End Controller */
