<?php if (!defined('BASEPATH')) exit('No direct script access allowed');



/* Ref_polres.php */
/* HARVIACODE CRUD GENERATOR MVC/HMVC AJAX CRUD */
/* PENGEMBANG : MPAMPAM */
/* EMAIL : MPAMPAM5@GMAIL.COM */
/* FACEBOOK : https://www.facebook.com/mpampam */
/* Location: ./application/controllers/Ref_polres.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-09-18 22:24:36 */
/* http://harviacode.com */

 class Ref_polres extends MY_Controller{
  function __construct(){
      parent::__construct();
      $this->load->model('Ref_polres_model','model');
      $this->load->library("Cl");
      if ($this->cl->acl(config_item("cpanel")."ref_polres")==false) {
        redirect("errors/er403");
      }
  }

 function _rules(){
		$this->form_validation->set_rules('id_pol', 'id_pol', 'trim');
		$this->form_validation->set_rules('nama', 'nama', 'trim|xss_clean|required');
		$this->form_validation->set_rules('telepon', 'telepon', 'trim|xss_clean|required');
		$this->form_validation->set_rules('alamat', 'alamat', 'trim|xss_clean|required');
		$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
  }

 function index(){
    $this->layouts->set_title('Polres/Polsek');
    $this->layouts->view(config_item("cpanel").'content/ref_polres/index');
  }

function json() {
    header('Content-Type: application/json');
    echo $this->model->json();
}


 function detail($id){
    if($row=$this->model->get_where($id)){
      $this->layouts->set_title('Polres/Polsek');
        $data=array('layout_title' => 'Polres/Polsek',
										'id_pol' => $row->id_pol,
										'nama' => $row->nama,
										'telepon' => $row->telepon,
										'alamat' => $row->alamat,
									);
				 // $this->layouts->view(config_item("cpanel").'content/ref_polres/detail',array(),$data);
//MODAL DETAIL
$this->layouts->view(config_item("cpanel").'content/ref_polres/detail',array(),$data,false);
    }else {
        $this->error_404();
    }
  }

 function tambah($status=''){
    if ($status=='aksi') {
        $json = array('success'=>false ,'alert'=>array());
        if ($this->input->is_ajax_request()) {
            $this->_rules();
            if ($this->form_validation->run()) {
                $insert = array(
																'nama' => $this->input->post('nama',TRUE),
																'telepon' => $this->input->post('telepon',TRUE),
																'alamat' => $this->input->post('alamat',TRUE),
															);
                $this->model->get_insert($insert);
                $json['alert']   = 'Berhasil Menyimpan!';
                $json['success'] = true;
            }else{
                foreach ($_POST as $key => $value) {
                  $json['alert'][$key] = form_error($key);
                }
            }
            echo json_encode($json);
        }
    }else{
      $this->layouts->set_title('Polres/Polsek');
      $data = array('layout_title' => 'Polres/Polsek',
                      'button'=>'tambah',
                      'aksi' =>site_url(config_item("cpanel").'ref_polres/tambah/aksi'),
											'id_pol' => set_value('id_pol'),
											'nama' => set_value('nama'),
											'telepon' => set_value('telepon'),
											'alamat' => set_value('alamat'),
											);
			 $this->layouts->view(config_item("cpanel").'content/ref_polres/form',array(),$data);
  //MODAL TAMBAH
  //$this->layouts->view(config_item("cpanel").'content/ref_polres/form',array(),$data,false);
     }
  }

 function edit($id,$status=''){
      if ($status=='aksi') {
          $json = array('success'=>false ,'alert'=>array());
          if ($this->input->is_ajax_request()) {
              $this->_rules();
              if ($this->form_validation->run()) {
                  $update = array(
																'nama' => $this->input->post('nama',TRUE),
																'telepon' => $this->input->post('telepon',TRUE),
																'alamat' => $this->input->post('alamat',TRUE),
															);
                $this->model->get_update($id,$update);
                $json['alert']   = 'Berhasil Mengedit!';
                $json['success'] = true;
            }else{
                foreach ($_POST as $key => $value) {
                  $json['alert'][$key] = form_error($key);
                }
            }
            echo json_encode($json);
        }
    }else{
      if($row=$this->model->get_where($id)){
        $this->layouts->set_title('Polres/Polsek');
        $data = array('layout_title' => 'Polres/Polsek',
                      'button'=>'edit',
                      'aksi' =>site_url(config_item("cpanel").'ref_polres/edit/'.$id.'/aksi'),
											'id_pol' => set_value('id_pol', $row->id_pol),
											'nama' => set_value('nama', $row->nama),
											'telepon' => set_value('telepon', $row->telepon),
											'alamat' => set_value('alamat', $row->alamat),
											);
			 $this->layouts->view(config_item("cpanel").'content/ref_polres/form',array(),$data);
  //MODAL EDIT
  //$this->layouts->view(config_item("cpanel").'content/ref_polres/form',array(),$data,false);
			}else{
      $this->error_404();
    }
  }
}

 function hapus($id){
  if ($this->input->is_ajax_request()) {
    if ($this->model->get_delete($id)==false) {
      $data['alert'] = 'Gagal Menghapus, data ini terpakai di table lain!';
    }else {
      $data['alert'] = 'Berhasil Menghapus!';
    }
      echo json_encode($data);
    }
}

}
/* End Controller */
