<?php if (!defined('BASEPATH')) exit('No direct script access allowed');



/* Ref_pekerjaan.php */
/* HARVIACODE CRUD GENERATOR MVC/HMVC AJAX CRUD */
/* PENGEMBANG : MPAMPAM */
/* EMAIL : MPAMPAM5@GMAIL.COM */
/* FACEBOOK : https://www.facebook.com/mpampam */
/* Location: ./application/controllers/Ref_pekerjaan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-08-31 20:51:55 */
/* http://harviacode.com */

 class Ref_pekerjaan extends MY_Controller{
  function __construct(){
      parent::__construct();
      $this->load->model('Ref_pekerjaan_model','model');
      $this->load->library("Cl");
      if ($this->cl->acl(config_item("cpanel")."ref_pekerjaan")==false) {
        redirect("errors/er403");
      }
  }

 function _rules(){
		$this->form_validation->set_rules('id_perkerjaan', 'id_perkerjaan', 'trim');
		$this->form_validation->set_rules('pekerjaan', 'pekerjaan', 'trim|xss_clean|required');
		$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
  }

 function index(){
    $this->layouts->set_title('Pekerjaan');
    $this->layouts->view(config_item("cpanel").'content/ref_pekerjaan/index');
  }

function json() {
    header('Content-Type: application/json');
    echo $this->model->json();
}


 function detail($id){
    if($row=$this->model->get_where($id)){
      $this->layouts->set_title('Pekerjaan');
        $data=array('layout_title' => 'Pekerjaan',
										'id_perkerjaan' => $row->id_perkerjaan,
										'pekerjaan' => $row->pekerjaan,
									);
				 $this->layouts->view(config_item("cpanel").'content/ref_pekerjaan/detail',array(),$data);
//MODAL DETAIL
//$this->layouts->view(config_item("cpanel").'content/ref_pekerjaan/detail',array(),$data,false);
    }else {
        $this->error_404();
    }
  }

 function tambah($status=''){
    if ($status=='aksi') {
        $json = array('success'=>false ,'alert'=>array());
        if ($this->input->is_ajax_request()) {
            $this->_rules();
            if ($this->form_validation->run()) {
                $insert = array(
																'pekerjaan' => $this->input->post('pekerjaan',TRUE),
															);
                $this->model->get_insert($insert);
                $json['alert']   = 'Berhasil Menyimpan!';
                $json['success'] = true;
            }else{
                foreach ($_POST as $key => $value) {
                  $json['alert'][$key] = form_error($key);
                }
            }
            echo json_encode($json);
        }
    }else{
      $this->layouts->set_title('Pekerjaan');
      $data = array('layout_title' => 'Pekerjaan',
                      'button'=>'tambah',
                      'aksi' =>site_url(config_item("cpanel").'ref_pekerjaan/tambah/aksi'),
											'id_perkerjaan' => set_value('id_perkerjaan'),
											'pekerjaan' => set_value('pekerjaan'),
											);
			 // $this->layouts->view(config_item("cpanel").'content/ref_pekerjaan/form',array(),$data);
  //MODAL TAMBAH
  $this->layouts->view(config_item("cpanel").'content/ref_pekerjaan/form',array(),$data,false);
     }
  }

 function edit($id,$status=''){
      if ($status=='aksi') {
          $json = array('success'=>false ,'alert'=>array());
          if ($this->input->is_ajax_request()) {
              $this->_rules();
              if ($this->form_validation->run()) {
                  $update = array(
																'pekerjaan' => $this->input->post('pekerjaan',TRUE),
															);
                $this->model->get_update($id,$update);
                $json['alert']   = 'Berhasil Mengedit!';
                $json['success'] = true;
            }else{
                foreach ($_POST as $key => $value) {
                  $json['alert'][$key] = form_error($key);
                }
            }
            echo json_encode($json);
        }
    }else{
      if($row=$this->model->get_where($id)){
        $this->layouts->set_title('Pekerjaan');
        $data = array('layout_title' => 'Pekerjaan',
                      'button'=>'edit',
                      'aksi' =>site_url(config_item("cpanel").'ref_pekerjaan/edit/'.$id.'/aksi'),
											'id_perkerjaan' => set_value('id_perkerjaan', $row->id_perkerjaan),
											'pekerjaan' => set_value('pekerjaan', $row->pekerjaan),
											);
			 //$this->layouts->view(config_item("cpanel").'content/ref_pekerjaan/form',array(),$data);
  //MODAL EDIT
  $this->layouts->view(config_item("cpanel").'content/ref_pekerjaan/form',array(),$data,false);
			}else{
      $this->error_404();
    }
  }
}

 function hapus($id){
  if ($this->input->is_ajax_request()) {
    if ($this->model->get_delete($id)==false) {
      $data['alert'] = 'Gagal Menghapus, data ini terpakai di table lain!';
    }else {
      $data['alert'] = 'Berhasil Menghapus!';
    }
      echo json_encode($data);
    }
}

}
/* End Controller */
