<?php if (!defined('BASEPATH')) exit('No direct script access allowed');



/* Ref_agama.php */
/* HARVIACODE CRUD GENERATOR MVC/HMVC AJAX CRUD */
/* PENGEMBANG : MPAMPAM */
/* EMAIL : MPAMPAM5@GMAIL.COM */
/* FACEBOOK : https://www.facebook.com/mpampam */
/* Location: ./application/controllers/Ref_agama.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-06-29 16:48:31 */
/* http://harviacode.com */

 class Ref_agama extends MY_Controller{
  function __construct(){
      parent::__construct();
      $this->load->model('Ref_agama_model','model');
      $this->load->library("Cl");
      if ($this->cl->acl(config_item("cpanel")."ref_agama")==false) {
        redirect("errors/er403");
      }
  }

 function _rules(){
		$this->form_validation->set_rules('id_agama', 'id_agama', 'trim');
		$this->form_validation->set_rules('agama', 'agama', 'trim|xss_clean|required');
		$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
  }

 function index(){
    $this->layouts->set_title('Agama');
    $this->layouts->view(config_item("cpanel").'content/ref_agama/index');
  }

function json() {
    header('Content-Type: application/json');
    echo $this->model->json();
}


 function detail($id){
    if($row=$this->model->get_where($id)){
      $this->layouts->set_title('Agama');
        $data=array('layout_title' => 'Ref_agama',
										'id_agama' => $row->id_agama,
										'agama' => $row->agama,
									);
				 //$this->layouts->view(config_item("cpanel").'content/ref_agama/detail',array(),$data);
//MODAL DETAIL
$this->layouts->view(config_item("cpanel").'content/ref_agama/detail',array(),$data,false);
    }else {
        $this->error_404();
    }
  }

 function tambah($status=''){
    if ($status=='aksi') {
        $json = array('success'=>false ,'alert'=>array());
        if ($this->input->is_ajax_request()) {
            $this->_rules();
            if ($this->form_validation->run()) {
                $insert = array(
																'agama' => $this->input->post('agama',TRUE),
																'created_at' => date('Y-m-d h:i:s'),
																'created_by' => sess('id_auth'),
															);
                $this->model->get_insert($insert);
                $json['alert']   = 'Berhasil Menyimpan!';
                $json['success'] = true;
            }else{
                foreach ($_POST as $key => $value) {
                  $json['alert'][$key] = form_error($key);
                }
            }
            echo json_encode($json);
        }
    }else{
      $this->layouts->set_title('Agama');
      $data = array('layout_title' => 'Ref_agama',
                      'button'=>'tambah',
                      'aksi' =>site_url(config_item("cpanel").'ref_agama/tambah/aksi'),
											'id_agama' => set_value('id_agama'),
											'agama' => set_value('agama'),
											);
			 //$this->layouts->view(config_item("cpanel").'content/ref_agama/form',array(),$data);
  //MODAL TAMBAH
  $this->layouts->view(config_item("cpanel").'content/ref_agama/form',array(),$data,false);
     }
  }

 function edit($id,$status=''){
      if ($status=='aksi') {
          $json = array('success'=>false ,'alert'=>array());
          if ($this->input->is_ajax_request()) {
              $this->_rules();
              if ($this->form_validation->run()) {
                  $update = array(
																'agama' => $this->input->post('agama',TRUE),
																'update_at' => date('Y-m-d h:i:s'),
																'update_by' => sess('id_auth'),
															);
                $this->model->get_update($id,$update);
                $json['alert']   = 'Berhasil Mengedit!';
                $json['success'] = true;
            }else{
                foreach ($_POST as $key => $value) {
                  $json['alert'][$key] = form_error($key);
                }
            }
            echo json_encode($json);
        }
    }else{
      if($row=$this->model->get_where($id)){
        $this->layouts->set_title('Agama');
        $data = array('layout_title' => 'Ref_agama',
                      'button'=>'edit',
                      'aksi' =>site_url(config_item("cpanel").'ref_agama/edit/'.$id.'/aksi'),
											'id_agama' => set_value('id_agama', $row->id_agama),
											'agama' => set_value('agama', $row->agama),
											);
			 //$this->layouts->view(config_item("cpanel").'content/ref_agama/form',array(),$data);
  //MODAL EDIT
  $this->layouts->view(config_item("cpanel").'content/ref_agama/form',array(),$data,false);
			}else{
      $this->error_404();
    }
  }
}

 function hapus($id){
  if ($this->input->is_ajax_request()) {
    if ($this->model->get_delete($id)==false) {
      $data['alert'] = 'Gagal Menghapus, data ini terpakai di table lain!';
    }else {
      $data['alert'] = 'Berhasil Menghapus!';
    }
      echo json_encode($data);
    }
}

}
/* End Controller */
