<?php if (!defined('BASEPATH')) exit('No direct script access allowed');



/* Trans_luka.php */
/* HARVIACODE CRUD GENERATOR MVC/HMVC AJAX CRUD */
/* PENGEMBANG : MPAMPAM */
/* EMAIL : MPAMPAM5@GMAIL.COM */
/* FACEBOOK : https://www.facebook.com/mpampam */
/* Location: ./application/controllers/Trans_luka.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-07-11 21:52:53 */
/* http://harviacode.com */

 class Trans_luka extends MY_Controller{
  function __construct(){
      parent::__construct();
      $this->load->model('Trans_luka_model','model');
      $this->load->library("Cl");
      if ($this->cl->acl(config_item("cpanel")."trans_luka")==false) {
        redirect("errors/er403");
      }
  }

 function _rules(){
		$this->form_validation->set_rules('id', 'id', 'trim');
		$this->form_validation->set_rules('id_rekam_medik', 'id rekam medik', 'trim|xss_clean|required');
		$this->form_validation->set_rules('jenis_luka', 'jenis luka', 'trim|xss_clean|required');
		$this->form_validation->set_rules('posisi_luka', 'posisi luka', 'trim|xss_clean|required');
		$this->form_validation->set_rules('foto', 'foto', 'trim|xss_clean|required');
		$this->form_validation->set_rules('created_at', 'created at', 'trim|xss_clean|required');
		$this->form_validation->set_rules('update_at', 'update at', 'trim|xss_clean|required');
		$this->form_validation->set_rules('created_by', 'created by', 'trim|xss_clean|required');
		$this->form_validation->set_rules('update_by', 'update by', 'trim|xss_clean|required');
		$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
  }

 function index(){
    $this->layouts->set_title('Data Luka');
    $this->layouts->view(config_item("cpanel").'content/trans_luka/index');
  }

function json() {
    header('Content-Type: application/json');
    echo $this->model->json();
}


 function detail($id){
    if($row=$this->model->get_where($id)){
      $this->layouts->set_title('Data Luka');
        $data=array('layout_title' => 'Data Luka',
										'id' => $row->id,
										'id_rekam_medik' => $row->id_rekam_medik,
										'jenis_luka' => $row->jenis_luka,
										'posisi_luka' => $row->posisi_luka,
										'foto' => $row->foto,
										'created_at' => $row->created_at,
										'update_at' => $row->update_at,
										'created_by' => $row->created_by,
										'update_by' => $row->update_by,
									);
				 $this->layouts->view(config_item("cpanel").'content/trans_luka/detail',array(),$data);
//MODAL DETAIL
//$this->layouts->view(config_item("cpanel").'content/trans_luka/detail',array(),$data,false);
    }else {
        $this->error_404();
    }
  }

 function tambah($status=''){
    if ($status=='aksi') {
        $json = array('success'=>false ,'alert'=>array());
        if ($this->input->is_ajax_request()) {
            $this->_rules();
            if ($this->form_validation->run()) {
                $insert = array(
																'id_rekam_medik' => $this->input->post('id_rekam_medik',TRUE),
																'jenis_luka' => $this->input->post('jenis_luka',TRUE),
																'posisi_luka' => $this->input->post('posisi_luka',TRUE),
																'foto' => $this->input->post('foto',TRUE),
																'created_at' => $this->input->post('created_at',TRUE),
																'update_at' => $this->input->post('update_at',TRUE),
																'created_by' => $this->input->post('created_by',TRUE),
																'update_by' => $this->input->post('update_by',TRUE),
															);
                $this->model->get_insert($insert);
                $json['alert']   = 'Berhasil Menyimpan!';
                $json['success'] = true;
            }else{
                foreach ($_POST as $key => $value) {
                  $json['alert'][$key] = form_error($key);
                }
            }
            echo json_encode($json);
        }
    }else{
      $this->layouts->set_title('Data Luka');
      $data = array('layout_title' => 'Data Luka',
                      'button'=>'tambah',
                      'aksi' =>site_url(config_item("cpanel").'trans_luka/tambah/aksi'),
											'id' => set_value('id'),
											'id_rekam_medik' => set_value('id_rekam_medik'),
											'jenis_luka' => set_value('jenis_luka'),
											'posisi_luka' => set_value('posisi_luka'),
											'foto' => set_value('foto'),
											'created_at' => set_value('created_at'),
											'update_at' => set_value('update_at'),
											'created_by' => set_value('created_by'),
											'update_by' => set_value('update_by'),
											);
			 $this->layouts->view(config_item("cpanel").'content/trans_luka/form',array(),$data);
  //MODAL TAMBAH
  //$this->layouts->view(config_item("cpanel").'content/trans_luka/form',array(),$data,false);
     }
  }

 function edit($id,$status=''){
      if ($status=='aksi') {
          $json = array('success'=>false ,'alert'=>array());
          if ($this->input->is_ajax_request()) {
              $this->_rules();
              if ($this->form_validation->run()) {
                  $update = array(
																'id_rekam_medik' => $this->input->post('id_rekam_medik',TRUE),
																'jenis_luka' => $this->input->post('jenis_luka',TRUE),
																'posisi_luka' => $this->input->post('posisi_luka',TRUE),
																'foto' => $this->input->post('foto',TRUE),
																'created_at' => $this->input->post('created_at',TRUE),
																'update_at' => $this->input->post('update_at',TRUE),
																'created_by' => $this->input->post('created_by',TRUE),
																'update_by' => $this->input->post('update_by',TRUE),
															);
                $this->model->get_update($id,$update);
                $json['alert']   = 'Berhasil Mengedit!';
                $json['success'] = true;
            }else{
                foreach ($_POST as $key => $value) {
                  $json['alert'][$key] = form_error($key);
                }
            }
            echo json_encode($json);
        }
    }else{
      if($row=$this->model->get_where($id)){
        $this->layouts->set_title('Data Luka');
        $data = array('layout_title' => 'Data Luka',
                      'button'=>'edit',
                      'aksi' =>site_url(config_item("cpanel").'trans_luka/edit/'.$id.'/aksi'),
											'id' => set_value('id', $row->id),
											'id_rekam_medik' => set_value('id_rekam_medik', $row->id_rekam_medik),
											'jenis_luka' => set_value('jenis_luka', $row->jenis_luka),
											'posisi_luka' => set_value('posisi_luka', $row->posisi_luka),
											'foto' => set_value('foto', $row->foto),
											'created_at' => set_value('created_at', $row->created_at),
											'update_at' => set_value('update_at', $row->update_at),
											'created_by' => set_value('created_by', $row->created_by),
											'update_by' => set_value('update_by', $row->update_by),
											);
			 $this->layouts->view(config_item("cpanel").'content/trans_luka/form',array(),$data);
  //MODAL EDIT
  //$this->layouts->view(config_item("cpanel").'content/trans_luka/form',array(),$data,false);
			}else{
      $this->error_404();
    }
  }
}

 function hapus($id){
  if ($this->input->is_ajax_request()) {
      $this->model->get_delete($id);
      $data['alert'] = 'Berhasil menghapus!';
      echo json_encode($data);
    }
}

}
/* End Controller */
