<?php

if (!defined('BASEPATH'))exit('No direct script access allowed');



/* */
/* HARVIACODE CRUD GENERATOR MVC/HMVC AJAX CRUD */
/* PENGEMBANG : MPAMPAM */
/* EMAIL : MPAMPAM5@GMAIL.COM */
/* FACEBOOK : https://www.facebook.com/mpampam */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-09-18 18:41:17 */
/* http://harviacode.com */

 class Mst_dokter_model extends CI_Model{
  var $table = 'mst_dokter';
  var $id    = 'id_pemeriksa';

    // datatables
      function json() {
          $this->datatables->select('id_pemeriksa,nik,nama');
          $this->datatables->from('mst_dokter');
          //add this line for join
          //$this->datatables->join('table2', 'mst_dokter.field = table2.field');
          $this->datatables->add_column('action',
          '<a href="'.site_url(config_item("cpanel")."mst_dokter/detail/$1").'" id="detail" class=""><i class="fa fa-eye"></i> detail</a>&nbsp;&nbsp;
           <a href="'.site_url(config_item("cpanel")."mst_dokter/edit/$1").'" id="edit" class=""><i class="fa fa-pencil"></i> edit</a>&nbsp;&nbsp;
           <a href="'.site_url(config_item("cpanel")."mst_dokter/hapus/$1").'" id="hapus" class=""><i class="fa fa-trash"></i> hapus</a>',
           'id_pemeriksa');
          return $this->datatables->generate();
      }


     function get_data()
      {
        return $this->db->query("SELECT * FROM $this->table ORDER BY $this->id DESC");
      }


      function get_insert($data)
        {
          return $this->db->insert($this->table,$data);
        }


      function get_where($where)
        {
          return $this->db->where($this->id,$where)
                          ->get($this->table)
                          ->row();
        }


      function get_update($where,$data)
        {
          return $this->db
                ->where($this->id,$where)
                ->update($this->table,$data);
        }


      function get_delete($where)
        {

          $query = $this->db->where($this->id,$where)
                          ->delete($this->table);
          if (!$query) {
            return false;
          }else {
            return true;
          }
        }

}
  /* End Model */
