<?php

if (!defined('BASEPATH'))exit('No direct script access allowed');



/* */
/* HARVIACODE CRUD GENERATOR MVC/HMVC AJAX CRUD */
/* PENGEMBANG : MPAMPAM */
/* EMAIL : MPAMPAM5@GMAIL.COM */
/* FACEBOOK : https://www.facebook.com/mpampam */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-07-01 18:15:21 */
/* http://harviacode.com */

 class Mst_tahanan_model extends CI_Model{
  var $table = 'mst_tahanan';
  var $id    = 'id_tahanan';

    // datatables
      function json() {
          $this->datatables->select('id_tahanan,nik,nama,tempat_lahir,DATE_FORMAT(tgl_lahir,"%d-%m-%Y") AS tgl_lahir,jenis_kelamin,kebangsaan,pekerjaan');
          $this->datatables->from('mst_tahanan');
          //add this line for join
          //$this->datatables->join('table2', 'mst_tahanan.field = table2.field');
          $this->datatables->add_column('action',
          '
          <a href="'.site_url(config_item("cpanel")."trans_rekam_medis/tambah").'?status=ya&id_tahanan=$1" id="rekam" class=""><i class="fa fa-medkit"></i></a>&nbsp;&nbsp;
            <a href="'.site_url(config_item("cpanel")."mst_tahanan/detail/$1").'" id="detail" class=""><i class="fa fa-eye"></i></a>&nbsp;&nbsp;
           <a href="'.site_url(config_item("cpanel")."mst_tahanan/edit/$1").'" id="edit" class=""><i class="fa fa-pencil"></i></a>&nbsp;&nbsp;
           <a href="'.site_url(config_item("cpanel")."mst_tahanan/hapus/$1").'" id="hapus" class=""><i class="fa fa-trash"></i></a>',
           'id_tahanan');
          return $this->datatables->generate();
      }


     function get_data()
      {
        return $this->db->query("SELECT * FROM $this->table ORDER BY $this->id DESC");
      }


      function get_insert($data)
        {
          return $this->db->insert($this->table,$data);
        }


      function get_where($where)
        {
          return $this->db->where($this->id,$where)
                          ->get($this->table)
                          ->row();
        }


      function get_update($where,$data)
        {
          return $this->db
                ->where($this->id,$where)
                ->update($this->table,$data);
        }


      function get_delete($where)
        {
          $query = $this->db->where($this->id,$where)
                          ->delete($this->table);
          if (!$query) {
            return false;
          }else {
            return true;
          }
        }

}
  /* End Model */
