<?php

if (!defined('BASEPATH'))exit('No direct script access allowed');



/* */
/* HARVIACODE CRUD GENERATOR MVC/HMVC AJAX CRUD */
/* PENGEMBANG : MPAMPAM */
/* EMAIL : MPAMPAM5@GMAIL.COM */
/* FACEBOOK : https://www.facebook.com/mpampam */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-07-06 20:16:44 */
/* http://harviacode.com */

 class Trans_rekam_medis_model extends CI_Model{
  var $table = 'trans_rekam_medis';
  var $id    = 'id';

    // datatables
      function json() {
          $this->datatables->select('trans_rekam_medis.id,kode,trans_rekam_medis.id_tahanan,trans_rekam_medis.id_dokter,mst_dokter.nama as dokter,mst_tahanan.nama as tahanan,mst_tahanan.nik,DATE_FORMAT(tgl_pemeriksaan,"%d-%m-%Y") AS tgl_pemeriksaan,trans_rekam_medis.rutan AS rutan,ref_polres.nama as nama_rutan,perkara,DATE_FORMAT(tgl_masuk,"%d-%m-%Y") AS tgl_masuk');
          $this->datatables->from('trans_rekam_medis');
          //add this line for join
          $this->datatables->join('ref_polres', 'trans_rekam_medis.rutan= ref_polres.id_pol','left');
          $this->datatables->join('mst_tahanan', 'trans_rekam_medis.id_tahanan = mst_tahanan.id_tahanan','left');
          $this->datatables->join('mst_dokter', 'trans_rekam_medis.id_dokter = mst_dokter.id_pemeriksa','left');
          $this->datatables->add_column('action',
          '<a href="'.site_url(config_item("cpanel")."trans_rekam_medis/detail/$1").'" id="detail" data-toggle="tooltip" data-placement="bottom" title="DETAIL" class="btn btn-xs btn-info"><i class="fa fa-file"></i></a>&nbsp;
          <a href="'.site_url(config_item("cpanel")."trans_rekam_medis/cetak/$1").'" target="_blank" id="cetak" data-toggle="tooltip" data-placement="bottom" title="CETAK" class="btn btn-xs btn-success"><i class="fa fa-print"></i></a>&nbsp;
           <a href="'.site_url(config_item("cpanel")."trans_rekam_medis/edit/$1").'"  id="edit" id="cetak" data-toggle="tooltip" data-placement="bottom" title="EDIT" class="btn btn-xs btn-warning"><i class="fa fa-pencil"></i></a>&nbsp;
           <a href="'.site_url(config_item("cpanel")."trans_rekam_medis/hapus/$1").'" id="hapus" data-toggle="tooltip" data-placement="bottom" title="HAPUS" class="btn btn-xs btn-danger"><i class="fa fa-trash"></i></a>',
           'id');
          return $this->datatables->generate();
      }

      function get_where_join($where)
        {
        $query =  $this->db->select('
                              trans_rekam_medis.id AS id,
                              trans_rekam_medis.kode,
                              trans_rekam_medis.id_tahanan,
                              trans_rekam_medis.id_dokter,
                              trans_rekam_medis.perkara,
                              trans_rekam_medis.rutan,
                              trans_rekam_medis.tgl_masuk,
                              trans_rekam_medis.tgl_pemeriksaan,
                              trans_rekam_medis.tinggi_badan,
                              trans_rekam_medis.berat_badan,
                              trans_rekam_medis.suhu_badan,
                              trans_rekam_medis.tensi_darah,
                              trans_rekam_medis.denyut_nadi,
                              trans_rekam_medis.pernapasan,
                              trans_rekam_medis.riwayat_penyakit,
                              trans_rekam_medis.keluhan,
                              trans_rekam_medis.pemeriksaan_tubuh,
                              trans_rekam_medis.therapi,
                              trans_rekam_medis.usulan,
                              trans_rekam_medis.created_at,
                              trans_rekam_medis.update_at,
                              trans_rekam_medis.created_by,
                              trans_rekam_medis.update_by,
                              ref_polres.nama AS nama_rutan,
                              mst_dokter.id_pemeriksa,
                              mst_dokter.nik AS nik_dokter,
                              mst_dokter.nama AS dokter,
                              mst_tahanan.id_tahanan,
                              mst_tahanan.nik AS nik_tahanan,
                              mst_tahanan.nama AS tahanan,
                              mst_tahanan.tempat_lahir,
                              mst_tahanan.tgl_lahir,
                              mst_tahanan.jenis_kelamin,
                              mst_tahanan.kebangsaan,
                              mst_tahanan.id_agama,
                              mst_tahanan.pekerjaan,
                              mst_tahanan.alamat,
                              mst_tahanan.foto,
                              ref_pekerjaan.id_perkerjaan AS id_perkerjaan,
                              ref_pekerjaan.pekerjaan AS nama_pekerjaan,
                              ref_agama.id_agama,
                              ref_agama.agama
                            ')

                    ->from('trans_rekam_medis')
                    ->join('ref_polres', 'trans_rekam_medis.rutan = ref_polres.id_pol','left')
                    ->join('mst_dokter', 'trans_rekam_medis.id_dokter = mst_dokter.id_pemeriksa','left')
                    ->join('mst_tahanan', 'trans_rekam_medis.id_tahanan = mst_tahanan.id_tahanan','left')
                    ->join('ref_pekerjaan', 'mst_tahanan.pekerjaan = ref_pekerjaan.id_perkerjaan','left')
                    ->join('ref_agama', 'mst_tahanan.id_agama = ref_agama.id_agama','left')
                    ->where('id',$where)
                    ->get();
          return $query->row();
        }


     function get_data()
      {
        return $this->db->query("SELECT * FROM $this->table ORDER BY $this->id DESC");
      }


      function get_insert($data)
        {
          return $this->db->insert($this->table,$data);
        }


      function get_where($where)
        {
          return $this->db->where($this->id,$where)
                          ->get($this->table)
                          ->row();
        }


      function get_update($where,$data)
        {
          return $this->db
                ->where($this->id,$where)
                ->update($this->table,$data);
        }


      function get_delete($where)
        {
          return $this->db->where($this->id,$where)
                          ->delete($this->table);
        }

        function luka_json($id) {
            $this->datatables->select('id,id_rekam_medik,jenis_luka,posisi_luka,foto,keterangan');
            $this->datatables->from('trans_luka');
            $this->datatables->where('id_rekam_medik',$id);
            //add this line for join
            $this->datatables->add_column('action',
             '<a href="'.site_url(config_item("cpanel")."trans_rekam_medis/modal_edit_luka/$1").'"  id="edit_luka" id="cetak" data-toggle="tooltip" data-placement="bottom" title="EDIT" class="btn btn-xs btn-warning"><i class="fa fa-pencil"></i></a>&nbsp;
             <a href="'.site_url(config_item("cpanel")."trans_rekam_medis/hapus_luka/$1").'" id="hapus_luka" data-toggle="tooltip" data-placement="bottom" title="HAPUS" class="btn btn-xs btn-danger"><i class="fa fa-trash"></i></a>',
             'id');
            return $this->datatables->generate();
        }

}
  /* End Model */
