<?php

if (!defined('BASEPATH'))exit('No direct script access allowed');



/* */
/* HARVIACODE CRUD GENERATOR MVC/HMVC AJAX CRUD */
/* PENGEMBANG : MPAMPAM */
/* EMAIL : MPAMPAM5@GMAIL.COM */
/* FACEBOOK : https://www.facebook.com/mpampam */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-07-11 21:52:53 */
/* http://harviacode.com */

 class Trans_luka_model extends CI_Model{
  var $table = 'trans_luka';
  var $id    = 'id';

    // datatables
      function json() {
          $this->datatables->select('id,id_rekam_medik,jenis_luka,posisi_luka,foto,created_at,update_at,created_by,update_by');
          $this->datatables->from('trans_luka');
          //add this line for join
          //$this->datatables->join('table2', 'trans_luka.field = table2.field');
          $this->datatables->add_column('action',
          '<a href="'.site_url(config_item("cpanel")."trans_luka/detail/$1").'" id="detail" class="btn btn-sm btn-primary">detail</a>
           <a href="'.site_url(config_item("cpanel")."trans_luka/edit/$1").'" id="edit" class="btn btn-sm btn-warning">edit</a>
           <a href="'.site_url(config_item("cpanel")."trans_luka/hapus/$1").'" id="hapus" class="btn btn-sm btn-danger">hapus</a>',
           'id');
          return $this->datatables->generate();
      }


     function get_data()
      {
        return $this->db->query("SELECT * FROM $this->table ORDER BY $this->id DESC");
      }


      function get_insert($data)
        {
          return $this->db->insert($this->table,$data);
        }


      function get_where($where)
        {
          return $this->db->where($this->id,$where)
                          ->get($this->table)
                          ->row();
        }


      function get_update($where,$data)
        {
          return $this->db
                ->where($this->id,$where)
                ->update($this->table,$data);
        }


      function get_delete($where)
        {
          return $this->db->where($this->id,$where)
                          ->delete($this->table);
        }

}
  /* End Model */
  